"""empty message

Revision ID: 06f60747851a
Revises: 8d8f75c2a6e1
Create Date: 2022-08-18 17:12:34.820238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f60747851a'
down_revision = '8d8f75c2a6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
