"""empty message

Revision ID: 5b099c7fb75f
Revises: 06f60747851a
Create Date: 2022-08-18 17:15:20.916431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b099c7fb75f'
down_revision = '06f60747851a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_text', sa.String(), nullable=True),
    sa.Column('user_filter', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('delivered', 'failed', name='messagestatus'), nullable=True),
    sa.Column('mailing_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('mailings')
    # ### end Alembic commands ###
